#ifndef TTYKEY_H
#define TTYKEY_H TTYKEY_H

typedef enum TTY_KEY {
	TTY_KEY_NORMAL,
	TTY_KEY_CTRL_A,
	TTY_KEY_CTRL_B,
	TTY_KEY_CTRL_C,
	TTY_KEY_CTRL_D,
	TTY_KEY_CTRL_E,
	TTY_KEY_CTRL_F,
	TTY_KEY_CTRL_G,
	TTY_KEY_CTRL_H,
	TTY_KEY_CTRL_I,
	TTY_KEY_CTRL_J,
	TTY_KEY_CTRL_K,
	TTY_KEY_CTRL_L,
	TTY_KEY_CTRL_M,
	TTY_KEY_CTRL_N,
	TTY_KEY_CTRL_O,
	TTY_KEY_CTRL_P,
	TTY_KEY_CTRL_Q,
	TTY_KEY_CTRL_R,
	TTY_KEY_CTRL_S,
	TTY_KEY_CTRL_T,
	TTY_KEY_CTRL_U,
	TTY_KEY_CTRL_V,
	TTY_KEY_CTRL_W,
	TTY_KEY_CTRL_X,
	TTY_KEY_CTRL_Y,
	TTY_KEY_CTRL_Z,
	TTY_KEY_ESC,
	TTY_KEY_BACKSPACE,
	TTY_KEY_LEFT,
	TTY_KEY_RIGHT,
    TTY_KEY_UP,
    TTY_KEY_DOWN,
	TTY_KEY_HOME,
	TTY_KEY_PAGEUP,
	TTY_KEY_PAGEDOWN
} TTY_KEY;

#endif
